apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  namespace: {{ .Release.Namespace }}

spec:
  type: ClusterIP

  selector:
    app: nginx-app

  ports:
    - name: http
      port: 81
      targetPort: 80
      protocol: TCP
